### ISSUE TITLE
For FFCS course registration as well

### ISSUE THREAD

**Issue by booleanbalaji** [karthikb351/AutoCaptcha-for-VITacademics#10]
Every second counts.

http://52.74.56.139/registration/ffcs_login.asp

**Comment by friendkvvk** [comment]
Hey bro,

Every semester, they will change the link. :)

**Comment by booleanbalaji** [comment]
We'll just update the link when they update it.

**Comment by karthikb351** [comment]
@booleanbalaji: Semma unfair advantage it'll give da.
