### ISSUE TITLE
IRCTC next? 

### ISSUE THREAD

**Issue by viraj89** [karthikb351/AutoCaptcha-for-VITacademics#13]
How can we make that happen for the IRCTC website? 

That could save 10 seconds.

**Comment by karthikb351** [comment]
The Tatkal captcha is hard to crack, the ones during normal timings is relatively straightforward.

Thanks for reminding me about this, will look into it today/tomorrow :)

**Comment by karthikb351** [comment]
As requested :) - https://github.com/karthikb351/AutoCaptcha-for-IRCTC
