### ISSUE TITLE
How to modify the code according to other website like irctc

### ISSUE THREAD

**Issue by sapientram** [karthikb351/AutoCaptcha-for-VITacademics#9]
Hi Karthik,

I wanted to read captcha from irctc website. Please kindly tell me how to change the source code and steps to do modify the code according to our requirement. Currently this extension is working for only academics website right.

So can you help me on the above problem.

Thanks
Ram

**Comment by rahulkapoor90** [comment]
Maybe you would have to change this 
var img = document.getElementById('imgCaptcha'); in captcha.js and also some more things.

**Comment by aneesh-neelam** [comment]
This captcha parser is specifically made for VIT's websites. It isn't going to work for the others at all. 
@karthikb351: I suggest you rename the project and repository for less ambiguity.

**Comment by rahulkapoor90** [comment]
@aneesh-neelam that clears the doubt, thanks.

**Comment by viraj89** [comment]
@all - As @aneesh-neelam has mentioned, yes, its specifically for a single URL for VIT academics. Also @karthikb351 has named it as VITacademics FYI. 

Happy thing is, @karthikb351 has roared out the same stuff for IRCTC here - https://github.com/karthikb351/AutoCaptcha-for-IRCTC
